# Generated by Django 5.0 on 2023-12-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user', models.CharField(max_length=200, verbose_name='ایمیل کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'باشگاه مشتریان',
            },
        ),
    ]
