# Generated by Django 5.0 on 2023-12-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_user',
            field=models.CharField(max_length=200, verbose_name='شماره تلفن کاربر'),
        ),
    ]
