# Generated by Django 5.0 on 2023-12-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_product_materials_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='علاقه مندی ها')),
            ],
            options={
                'verbose_name': 'علاقه مندی',
                'verbose_name_plural': 'علاقه مندی ها',
            },
        ),
    ]
