# Generated by Django 5.0 on 2023-12-25 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_shop', '0002_like_products_user_id'),
        ('products', '0009_alter_product_ranking_alter_product_ranking_avg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pade', models.BooleanField(verbose_name='واریز شده / نشده')),
                ('is_post', models.BooleanField(default=False, verbose_name='پرداخت درب منزل')),
                ('peyment_date', models.CharField(blank=True, default='۱۴۰۲-۱۰-۰۴', max_length=200, null=True, verbose_name='تاریخ واریز')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارشات',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'جزییات سفارشات',
                'verbose_name_plural': 'جزییات سفارشات',
            },
        ),
    ]
