# Generated by Django 5.0 on 2023-12-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_shop', '0003_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_post',
            field=models.BooleanField(default=False, verbose_name='ارسال با پست'),
        ),
    ]
