# Generated by Django 5.0 on 2023-12-25 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_shop', '0005_order_is_post_send_alter_order_is_post'),
        ('products', '0009_alter_product_ranking_alter_product_ranking_avg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_pade',
            new_name='is_pay',
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='peyment_date',
            field=models.CharField(blank=True, default='۱۴۰۲/۱۰/۰۵', max_length=200, null=True, verbose_name='تاریخ ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_shop.order', verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='نام محصول'),
        ),
    ]
