# Generated by Django 5.0 on 2023-12-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_shop', '0009_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='واریز شده / نشده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='یاداشت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تلفن کاربر'),
        ),
    ]
