# Generated by Django 5.0 on 2023-12-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_shop', '0010_alter_order_fname_alter_order_is_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='peyment_date',
            field=models.CharField(blank=True, default='۱۴۰۲/۱۰/۱۱', max_length=200, null=True, verbose_name='تاریخ ثبت سفارش'),
        ),
    ]
