# Generated by Django 5.0 on 2024-01-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_shop', '0012_alter_order_peyment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='peyment_date',
            field=models.CharField(blank=True, default='1402/11/07', max_length=200, null=True, verbose_name='تاریخ ثبت سفارش'),
        ),
    ]
