# Generated by Django 5.0 on 2023-12-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_alter_blog_date_alter_blog_date_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField(max_length=200, verbose_name='نظر کاربر')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='نام مقاله')),
            ],
            options={
                'verbose_name': 'نظرات',
                'verbose_name_plural': 'نظرات مقالات',
            },
        ),
    ]
