# Generated by Django 5.0 on 2023-12-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_product'),
        ('products', '0006_product_materials_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_product',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='نام محصول'),
            preserve_default=False,
        ),
    ]
