# Generated by Django 5.0 on 2023-12-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_product_product_id'),
        ('products', '0009_alter_product_ranking_alter_product_ranking_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_product',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_counts', to='products.product', verbose_name='نام محصول'),
        ),
    ]
