# Generated by Django 5.0 on 2023-12-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فارسی دسته بندی')),
                ('en_name', models.CharField(max_length=200, verbose_name='نام انگلیسی دسته بندی')),
            ],
            options={
                'verbose_name': 'مقالات',
                'verbose_name_plural': 'اضافه کردن مقالات',
            },
        ),
    ]
