# Generated by Django 5.0 on 2023-12-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category',
            options={'verbose_name': 'دسته بندی جدید', 'verbose_name_plural': 'اضافه کردن دسته بندی مقالات'},
        ),
    ]
