# Generated by Django 5.0 on 2023-12-15 08:47

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام مقاله')),
                ('date', models.CharField(default='۱۴۰۲-۰۹-۲۴', max_length=100, verbose_name='تاریخ')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر مقاله')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن مقاله')),
                ('writer', models.CharField(max_length=100, verbose_name='نام نویسنده')),
                ('wr_image', models.ImageField(upload_to='', verbose_name='تصویر نویسنده')),
                ('about', models.TextField(blank=True, max_length=300, null=True, verbose_name='درباره نویسنده')),
                ('new', models.BooleanField(verbose_name='جدید')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog_category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'اضافه کردن مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
