# Generated by Django 5.0 on 2023-12-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='blog',
            name='date_number',
            field=models.DecimalField(decimal_places=0, default='۱۴۰۲۰۹۲۴', max_digits=20),
        ),
    ]
