# Generated by Django 5.0 on 2023-12-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options_blog_date_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='new',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_number',
            field=models.DecimalField(decimal_places=0, default=14020924, max_digits=20, verbose_name='این فیلد  تنظیم شده لطفا تغییر ندهید'),
        ),
    ]
