# Generated by Django 5.0 on 2023-12-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_new_alter_blog_date_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(default='۱۴۰۲-۰۹-۲۵', max_length=100, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_number',
            field=models.DecimalField(decimal_places=0, default=14020925, max_digits=20, verbose_name='این فیلد  تنظیم شده لطفا تغییر ندهید'),
        ),
    ]
