# Generated by Django 5.0 on 2023-12-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_date_alter_blog_date_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_number',
            field=models.DecimalField(decimal_places=0, default='۱۴۰۲۱۰۱۱', editable=False, max_digits=20, verbose_name='این فیلد  تنظیم شده لطفا تغییر ندهید'),
        ),
    ]
