# Generated by Django 5.0 on 2024-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_date_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(default=1, max_length=500, verbose_name='کلیدواژه ها را برای سئو وارد کنید (  با علامت , جدا کنید  )'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_seo',
            field=models.TextField(default=1, verbose_name='توضیحات متا برای سئو'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title_seo',
            field=models.CharField(default=1, max_length=500, verbose_name='عنوان برای سئو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(default='۱۴۰۲-۱۰-۲۰', max_length=100, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_number',
            field=models.DecimalField(decimal_places=0, default='۱۴۰۲۱۰۲۰', editable=False, max_digits=20, verbose_name='این فیلد  تنظیم شده لطفا تغییر ندهید'),
        ),
    ]
