# Generated by Django 5.0 on 2023-12-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_number',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.CharField(default=2, max_length=100, verbose_name='تاریخ'),
        ),
    ]
