# Generated by Django 5.0 on 2023-12-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_date_number_product_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products_category', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
