# Generated by Django 5.0 on 2023-12-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Materials',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='مواد تشکیل دهنده محصول ( اختیاری)'),
        ),
        migrations.AddField(
            model_name='product',
            name='Weight',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='وزن محصول ( اختیاری)'),
        ),
    ]
