# Generated by Django 5.0 on 2023-12-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_count_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ranking',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20, verbose_name='امتیاز های محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ranking_AVG',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='رنکینگ محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_buy',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='تعداد فروش'),
        ),
    ]
