# Generated by Django 5.0 on 2023-12-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_ranking_product_ranking_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ranking',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=20, verbose_name='امتیاز های محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ranking_AVG',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, editable=False, max_digits=20, null=True, verbose_name='رنکینگ محصول'),
        ),
    ]
