# Generated by Django 5.0 on 2023-12-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_ranking_alter_product_ranking_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.CharField(default='۱۴۰۲-۱۰-۱۱', max_length=100, verbose_name='تاریخ'),
        ),
    ]
