# Generated by Django 5.0 on 2024-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.CharField(default='۱۴۰۲-۱۰-۲۰', max_length=100, verbose_name='تاریخ'),
        ),
    ]
